@startuml name Adaptivität

class World {
  fileVersion: string
  amgVersion: string
  author: string
  language: string
  worldName: string
  worldUUID: string
  worldDescription: string
  worldGoals: string[]
  evaluationLink: string
}

class Topic {
  topicId: int
  topicName: string
  topicContents: int[]
}

class Space {
  spaceId: int
  spaceUUID: string
  spaceName: string
  spaceDescription: string
  spaceGoals: string[]
  spaceSlotContents: int[]
  requiredPointsToComplete: int
  requiredSpacesToEnter: string
  spaceTemplate: string
  spaceTemplateStyle: string
}

class Element {
  elementId: int
  elementUUID: string
  elementName: string
  elementDescription: string
  elementGoals: string[]
  elementCategory: string
  elementFileType: string
  elementMaxScore: int
  elementModel: string
}

class AdaptivityContent {
  shuffleQuestions: bool
  questions: Question[]
}

class Question {
  questionID: string
  questionTitle: string
  questionText: string
  questionImage: string
  questionPoints: int
  questionType: string
  questionAnswers: Answer[]
}

class Answer {
  answerIndex: int
  answerText: string
  answerImage: string
}

World --> Topic
World --> Space
World --> Element
Element --> AdaptivityContent
AdaptivityContent --> Question
Question --> Answer
@enduml